version: "3"

services:

  runtime-setup:
    image: async-http-client:22.04-5.8
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.8"

  documentation-check:
    image: async-http-client:22.04-5.8

  test:
    image: async-http-client:22.04-5.8
    environment:
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: async-http-client:22.04-5.8
